language: node_js
node_js:
  - 12.18.3

services:
  docker

script:
  - docker --version
  - docker build -t udagram-feed-api
  - docker tag udagram-feed-api elsrickle/udagram-feed-api:latest

after_success:
  - echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push elsrickle/udagram-user-api